-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ebpf_validate]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace ebpf_validate

/-- [ebpf_validate::Insn]
    Source: 'src/lib.rs', lines 36:0-42:1
    Visibility: public -/
structure Insn where
  opcode : Std.U8
  dst : Std.U8
  src : Std.U8
  offset : Std.I16
  imm : Std.I32

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Insn}::clone]:
    Source: 'src/lib.rs', lines 34:15-34:20
    Visibility: public -/
def Insn.Insts.CoreCloneClone.clone (self : Insn) : Result Insn := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Insn}]
    Source: 'src/lib.rs', lines 34:15-34:20 -/
@[reducible]
def Insn.Insts.CoreCloneClone : core.clone.Clone Insn := {
  clone := Insn.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::Insn}]
    Source: 'src/lib.rs', lines 34:9-34:13 -/
@[reducible]
def Insn.Insts.CoreMarkerCopy : core.marker.Copy Insn := {
  cloneInst := Insn.Insts.CoreCloneClone
}

/-- [ebpf_validate::Config]
    Source: 'src/lib.rs', lines 47:0-57:1
    Visibility: public -/
structure Config where
  instruction_limit : Std.Usize
  has_dispatcher : Bool
  accept_every_helper : Bool

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Config}::clone]:
    Source: 'src/lib.rs', lines 45:15-45:20
    Visibility: public -/
def Config.Insts.CoreCloneClone.clone (self : Config) : Result Config := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Config}]
    Source: 'src/lib.rs', lines 45:15-45:20 -/
@[reducible]
def Config.Insts.CoreCloneClone : core.clone.Clone Config := {
  clone := Config.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::Config}]
    Source: 'src/lib.rs', lines 45:9-45:13 -/
@[reducible]
def Config.Insts.CoreMarkerCopy : core.marker.Copy Config := {
  cloneInst := Config.Insts.CoreCloneClone
}

/-- [ebpf_validate::Reject]
    Source: 'src/lib.rs', lines 63:0-92:1
    Visibility: public -/
@[discriminant isize]
inductive Reject where
| TooManyInstructions : Reject
| UnknownOpcode : Std.Usize → Reject
| NegSrc : Std.Usize → Reject
| EndianImm : Std.Usize → Reject
| LddwSrc : Std.Usize → Reject
| IncompleteLddw : Std.Usize → Reject
| LddwSecondHalf : Std.Usize → Reject
| AtomicUnknown : Std.Usize → Reject
| AtomicNeedsFetch : Std.Usize → Reject
| InfiniteLoop : Std.Usize → Reject
| JumpOutOfBounds : Std.Usize → Reject
| JumpIntoLddw : Std.Usize → Reject
| CrossSectionMetadata : Std.Usize → Reject
| HelperImm : Std.Usize → Reject
| UnknownHelper : Std.Usize → Reject
| LocalCallOutOfBounds : Std.Usize → Reject
| CallIntoLddw : Std.Usize → Reject
| BtfCall : Std.Usize → Reject
| CallType : Std.Usize → Reject
| InvalidSrc : Std.Usize → Reject
| InvalidDst : Std.Usize → Reject
| FilterOpcode : Std.Usize → Reject
| FilterDst : Std.Usize → Reject
| FilterSrc : Std.Usize → Reject
| FilterImm : Std.Usize → Reject
| FilterOffset : Std.Usize → Reject
| SubProgramJump : Std.Usize → Reject
| SubProgramEnd : Std.Usize → Reject

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Reject}::clone]:
    Source: 'src/lib.rs', lines 61:15-61:20
    Visibility: public -/
def Reject.Insts.CoreCloneClone.clone (self : Reject) : Result Reject := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Reject}]
    Source: 'src/lib.rs', lines 61:15-61:20 -/
@[reducible]
def Reject.Insts.CoreCloneClone : core.clone.Clone Reject := {
  clone := Reject.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::Reject}]
    Source: 'src/lib.rs', lines 61:9-61:13 -/
@[reducible]
def Reject.Insts.CoreMarkerCopy : core.marker.Copy Reject := {
  cloneInst := Reject.Insts.CoreCloneClone
}

/-- [ebpf_validate::CLS_MASK]
    Source: 'src/lib.rs', lines 98:0-98:30
    Visibility: public -/
@[global_simps, irreducible] def CLS_MASK : Std.U8 := 7#u8

/-- [ebpf_validate::CLS_LD]
    Source: 'src/lib.rs', lines 99:0-99:28
    Visibility: public -/
@[global_simps, irreducible] def CLS_LD : Std.U8 := 0#u8

/-- [ebpf_validate::CLS_LDX]
    Source: 'src/lib.rs', lines 100:0-100:29
    Visibility: public -/
@[global_simps, irreducible] def CLS_LDX : Std.U8 := 1#u8

/-- [ebpf_validate::CLS_ST]
    Source: 'src/lib.rs', lines 101:0-101:28
    Visibility: public -/
@[global_simps, irreducible] def CLS_ST : Std.U8 := 2#u8

/-- [ebpf_validate::CLS_STX]
    Source: 'src/lib.rs', lines 102:0-102:29
    Visibility: public -/
@[global_simps, irreducible] def CLS_STX : Std.U8 := 3#u8

/-- [ebpf_validate::CLS_ALU]
    Source: 'src/lib.rs', lines 103:0-103:29
    Visibility: public -/
@[global_simps, irreducible] def CLS_ALU : Std.U8 := 4#u8

/-- [ebpf_validate::CLS_JMP]
    Source: 'src/lib.rs', lines 104:0-104:29
    Visibility: public -/
@[global_simps, irreducible] def CLS_JMP : Std.U8 := 5#u8

/-- [ebpf_validate::CLS_JMP32]
    Source: 'src/lib.rs', lines 105:0-105:31
    Visibility: public -/
@[global_simps, irreducible] def CLS_JMP32 : Std.U8 := 6#u8

/-- [ebpf_validate::CLS_ALU64]
    Source: 'src/lib.rs', lines 106:0-106:31
    Visibility: public -/
@[global_simps, irreducible] def CLS_ALU64 : Std.U8 := 7#u8

/-- [ebpf_validate::SRC_REG]
    Source: 'src/lib.rs', lines 108:0-108:29
    Visibility: public -/
@[global_simps, irreducible] def SRC_REG : Std.U8 := 8#u8

/-- [ebpf_validate::SIZE_MASK]
    Source: 'src/lib.rs', lines 110:0-110:31
    Visibility: public -/
@[global_simps, irreducible] def SIZE_MASK : Std.U8 := 24#u8

/-- [ebpf_validate::SIZE_W]
    Source: 'src/lib.rs', lines 111:0-111:28
    Visibility: public -/
@[global_simps, irreducible] def SIZE_W : Std.U8 := 0#u8

/-- [ebpf_validate::SIZE_H]
    Source: 'src/lib.rs', lines 112:0-112:28
    Visibility: public -/
@[global_simps, irreducible] def SIZE_H : Std.U8 := 8#u8

/-- [ebpf_validate::SIZE_B]
    Source: 'src/lib.rs', lines 113:0-113:28
    Visibility: public -/
@[global_simps, irreducible] def SIZE_B : Std.U8 := 16#u8

/-- [ebpf_validate::SIZE_DW]
    Source: 'src/lib.rs', lines 114:0-114:29
    Visibility: public -/
@[global_simps, irreducible] def SIZE_DW : Std.U8 := 24#u8

/-- [ebpf_validate::MODE_MASK]
    Source: 'src/lib.rs', lines 116:0-116:31
    Visibility: public -/
@[global_simps, irreducible] def MODE_MASK : Std.U8 := 224#u8

/-- [ebpf_validate::MODE_IMM]
    Source: 'src/lib.rs', lines 117:0-117:30
    Visibility: public -/
@[global_simps, irreducible] def MODE_IMM : Std.U8 := 0#u8

/-- [ebpf_validate::MODE_MEM]
    Source: 'src/lib.rs', lines 118:0-118:30
    Visibility: public -/
@[global_simps, irreducible] def MODE_MEM : Std.U8 := 96#u8

/-- [ebpf_validate::MODE_MEMSX]
    Source: 'src/lib.rs', lines 119:0-119:32
    Visibility: public -/
@[global_simps, irreducible] def MODE_MEMSX : Std.U8 := 128#u8

/-- [ebpf_validate::MODE_ATOMIC]
    Source: 'src/lib.rs', lines 120:0-120:33
    Visibility: public -/
@[global_simps, irreducible] def MODE_ATOMIC : Std.U8 := 192#u8

/-- [ebpf_validate::ALU_MASK]
    Source: 'src/lib.rs', lines 122:0-122:30
    Visibility: public -/
@[global_simps, irreducible] def ALU_MASK : Std.U8 := 240#u8

/-- [ebpf_validate::ALU_ADD]
    Source: 'src/lib.rs', lines 123:0-123:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_ADD : Std.U8 := 0#u8

/-- [ebpf_validate::ALU_SUB]
    Source: 'src/lib.rs', lines 124:0-124:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_SUB : Std.U8 := 16#u8

/-- [ebpf_validate::ALU_MUL]
    Source: 'src/lib.rs', lines 125:0-125:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_MUL : Std.U8 := 32#u8

/-- [ebpf_validate::ALU_DIV]
    Source: 'src/lib.rs', lines 126:0-126:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_DIV : Std.U8 := 48#u8

/-- [ebpf_validate::ALU_OR]
    Source: 'src/lib.rs', lines 127:0-127:28
    Visibility: public -/
@[global_simps, irreducible] def ALU_OR : Std.U8 := 64#u8

/-- [ebpf_validate::ALU_AND]
    Source: 'src/lib.rs', lines 128:0-128:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_AND : Std.U8 := 80#u8

/-- [ebpf_validate::ALU_LSH]
    Source: 'src/lib.rs', lines 129:0-129:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_LSH : Std.U8 := 96#u8

/-- [ebpf_validate::ALU_RSH]
    Source: 'src/lib.rs', lines 130:0-130:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_RSH : Std.U8 := 112#u8

/-- [ebpf_validate::ALU_NEG]
    Source: 'src/lib.rs', lines 131:0-131:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_NEG : Std.U8 := 128#u8

/-- [ebpf_validate::ALU_MOD]
    Source: 'src/lib.rs', lines 132:0-132:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_MOD : Std.U8 := 144#u8

/-- [ebpf_validate::ALU_XOR]
    Source: 'src/lib.rs', lines 133:0-133:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_XOR : Std.U8 := 160#u8

/-- [ebpf_validate::ALU_MOV]
    Source: 'src/lib.rs', lines 134:0-134:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_MOV : Std.U8 := 176#u8

/-- [ebpf_validate::ALU_ARSH]
    Source: 'src/lib.rs', lines 135:0-135:30
    Visibility: public -/
@[global_simps, irreducible] def ALU_ARSH : Std.U8 := 192#u8

/-- [ebpf_validate::ALU_END]
    Source: 'src/lib.rs', lines 136:0-136:29
    Visibility: public -/
@[global_simps, irreducible] def ALU_END : Std.U8 := 208#u8

/-- [ebpf_validate::JMP_MASK]
    Source: 'src/lib.rs', lines 138:0-138:30
    Visibility: public -/
@[global_simps, irreducible] def JMP_MASK : Std.U8 := 240#u8

/-- [ebpf_validate::JMP_JA]
    Source: 'src/lib.rs', lines 139:0-139:28
    Visibility: public -/
@[global_simps, irreducible] def JMP_JA : Std.U8 := 0#u8

/-- [ebpf_validate::JMP_JEQ]
    Source: 'src/lib.rs', lines 140:0-140:29
    Visibility: public -/
@[global_simps, irreducible] def JMP_JEQ : Std.U8 := 16#u8

/-- [ebpf_validate::JMP_JGT]
    Source: 'src/lib.rs', lines 141:0-141:29
    Visibility: public -/
@[global_simps, irreducible] def JMP_JGT : Std.U8 := 32#u8

/-- [ebpf_validate::JMP_JGE]
    Source: 'src/lib.rs', lines 142:0-142:29
    Visibility: public -/
@[global_simps, irreducible] def JMP_JGE : Std.U8 := 48#u8

/-- [ebpf_validate::JMP_JSET]
    Source: 'src/lib.rs', lines 143:0-143:30
    Visibility: public -/
@[global_simps, irreducible] def JMP_JSET : Std.U8 := 64#u8

/-- [ebpf_validate::JMP_JNE]
    Source: 'src/lib.rs', lines 144:0-144:29
    Visibility: public -/
@[global_simps, irreducible] def JMP_JNE : Std.U8 := 80#u8

/-- [ebpf_validate::JMP_JSGT]
    Source: 'src/lib.rs', lines 145:0-145:30
    Visibility: public -/
@[global_simps, irreducible] def JMP_JSGT : Std.U8 := 96#u8

/-- [ebpf_validate::JMP_JSGE]
    Source: 'src/lib.rs', lines 146:0-146:30
    Visibility: public -/
@[global_simps, irreducible] def JMP_JSGE : Std.U8 := 112#u8

/-- [ebpf_validate::JMP_CALL]
    Source: 'src/lib.rs', lines 147:0-147:30
    Visibility: public -/
@[global_simps, irreducible] def JMP_CALL : Std.U8 := 128#u8

/-- [ebpf_validate::JMP_EXIT]
    Source: 'src/lib.rs', lines 148:0-148:30
    Visibility: public -/
@[global_simps, irreducible] def JMP_EXIT : Std.U8 := 144#u8

/-- [ebpf_validate::JMP_JLT]
    Source: 'src/lib.rs', lines 149:0-149:29
    Visibility: public -/
@[global_simps, irreducible] def JMP_JLT : Std.U8 := 160#u8

/-- [ebpf_validate::JMP_JLE]
    Source: 'src/lib.rs', lines 150:0-150:29
    Visibility: public -/
@[global_simps, irreducible] def JMP_JLE : Std.U8 := 176#u8

/-- [ebpf_validate::JMP_JSLT]
    Source: 'src/lib.rs', lines 151:0-151:30
    Visibility: public -/
@[global_simps, irreducible] def JMP_JSLT : Std.U8 := 192#u8

/-- [ebpf_validate::JMP_JSLE]
    Source: 'src/lib.rs', lines 152:0-152:30
    Visibility: public -/
@[global_simps, irreducible] def JMP_JSLE : Std.U8 := 208#u8

/-- [ebpf_validate::ATOMIC_OP_FETCH]
    Source: 'src/lib.rs', lines 154:0-154:38
    Visibility: public -/
@[global_simps, irreducible] def ATOMIC_OP_FETCH : Std.I32 := 1#i32

/-- [ebpf_validate::ATOMIC_OP_XCHG]
    Source: 'src/lib.rs', lines 155:0-155:55
    Visibility: public -/
@[global_simps, irreducible]
def ATOMIC_OP_XCHG : Std.I32 := 224#i32 ||| ATOMIC_OP_FETCH

/-- [ebpf_validate::ATOMIC_OP_CMPXCHG]
    Source: 'src/lib.rs', lines 156:0-156:58
    Visibility: public -/
@[global_simps, irreducible]
def ATOMIC_OP_CMPXCHG : Std.I32 := 240#i32 ||| ATOMIC_OP_FETCH

/-- [ebpf_validate::OP_LDDW]
    Source: 'src/lib.rs', lines 158:0-158:29
    Visibility: public -/
@[global_simps, irreducible] def OP_LDDW : Std.U8 := 24#u8

/-- [ebpf_validate::OP_CALL]
    Source: 'src/lib.rs', lines 159:0-159:29
    Visibility: public -/
@[global_simps, irreducible] def OP_CALL : Std.U8 := 133#u8

/-- [ebpf_validate::OP_EXIT]
    Source: 'src/lib.rs', lines 160:0-160:29
    Visibility: public -/
@[global_simps, irreducible] def OP_EXIT : Std.U8 := 149#u8

/-- [ebpf_validate::OP_JA]
    Source: 'src/lib.rs', lines 161:0-161:27
    Visibility: public -/
@[global_simps, irreducible] def OP_JA : Std.U8 := 5#u8

/-- [ebpf_validate::OP_JA32]
    Source: 'src/lib.rs', lines 162:0-162:29
    Visibility: public -/
@[global_simps, irreducible] def OP_JA32 : Std.U8 := 6#u8

/-- [ebpf_validate::Width]
    Source: 'src/lib.rs', lines 166:0-171:1
    Visibility: public -/
@[discriminant isize]
inductive Width where
| B : Width
| H : Width
| W : Width
| DW : Width

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Width}::clone]:
    Source: 'src/lib.rs', lines 164:15-164:20
    Visibility: public -/
def Width.Insts.CoreCloneClone.clone (self : Width) : Result Width := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Width}]
    Source: 'src/lib.rs', lines 164:15-164:20 -/
@[reducible]
def Width.Insts.CoreCloneClone : core.clone.Clone Width := {
  clone := Width.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::Width}]
    Source: 'src/lib.rs', lines 164:9-164:13 -/
@[reducible]
def Width.Insts.CoreMarkerCopy : core.marker.Copy Width := {
  cloneInst := Width.Insts.CoreCloneClone
}

/-- [ebpf_validate::AluWidth]
    Source: 'src/lib.rs', lines 175:0-178:1
    Visibility: public -/
@[discriminant isize]
inductive AluWidth where
| W32 : AluWidth
| W64 : AluWidth

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::AluWidth}::clone]:
    Source: 'src/lib.rs', lines 173:15-173:20
    Visibility: public -/
def AluWidth.Insts.CoreCloneClone.clone
  (self : AluWidth) : Result AluWidth := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::AluWidth}]
    Source: 'src/lib.rs', lines 173:15-173:20 -/
@[reducible]
def AluWidth.Insts.CoreCloneClone : core.clone.Clone AluWidth := {
  clone := AluWidth.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::AluWidth}]
    Source: 'src/lib.rs', lines 173:9-173:13 -/
@[reducible]
def AluWidth.Insts.CoreMarkerCopy : core.marker.Copy AluWidth := {
  cloneInst := AluWidth.Insts.CoreCloneClone
}

/-- [ebpf_validate::Source]
    Source: 'src/lib.rs', lines 182:0-185:1
    Visibility: public -/
@[discriminant isize]
inductive Source where
| Imm : Source
| Reg : Source

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Source}::clone]:
    Source: 'src/lib.rs', lines 180:15-180:20
    Visibility: public -/
def Source.Insts.CoreCloneClone.clone (self : Source) : Result Source := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Source}]
    Source: 'src/lib.rs', lines 180:15-180:20 -/
@[reducible]
def Source.Insts.CoreCloneClone : core.clone.Clone Source := {
  clone := Source.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::Source}]
    Source: 'src/lib.rs', lines 180:9-180:13 -/
@[reducible]
def Source.Insts.CoreMarkerCopy : core.marker.Copy Source := {
  cloneInst := Source.Insts.CoreCloneClone
}

/-- [ebpf_validate::AluOp]
    Source: 'src/lib.rs', lines 189:0-203:1
    Visibility: public -/
@[discriminant isize]
inductive AluOp where
| Add : AluOp
| Sub : AluOp
| Mul : AluOp
| Div : AluOp
| Or : AluOp
| And : AluOp
| Lsh : AluOp
| Rsh : AluOp
| Neg : AluOp
| Mod : AluOp
| Xor : AluOp
| Mov : AluOp
| Arsh : AluOp

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::AluOp}::clone]:
    Source: 'src/lib.rs', lines 187:15-187:20
    Visibility: public -/
def AluOp.Insts.CoreCloneClone.clone (self : AluOp) : Result AluOp := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::AluOp}]
    Source: 'src/lib.rs', lines 187:15-187:20 -/
@[reducible]
def AluOp.Insts.CoreCloneClone : core.clone.Clone AluOp := {
  clone := AluOp.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::AluOp}]
    Source: 'src/lib.rs', lines 187:9-187:13 -/
@[reducible]
def AluOp.Insts.CoreMarkerCopy : core.marker.Copy AluOp := {
  cloneInst := AluOp.Insts.CoreCloneClone
}

/-- [ebpf_validate::JmpOp]
    Source: 'src/lib.rs', lines 207:0-219:1
    Visibility: public -/
@[discriminant isize]
inductive JmpOp where
| Eq : JmpOp
| Gt : JmpOp
| Ge : JmpOp
| Set : JmpOp
| Ne : JmpOp
| Sgt : JmpOp
| Sge : JmpOp
| Lt : JmpOp
| Le : JmpOp
| Slt : JmpOp
| Sle : JmpOp

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::JmpOp}::clone]:
    Source: 'src/lib.rs', lines 205:15-205:20
    Visibility: public -/
def JmpOp.Insts.CoreCloneClone.clone (self : JmpOp) : Result JmpOp := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::JmpOp}]
    Source: 'src/lib.rs', lines 205:15-205:20 -/
@[reducible]
def JmpOp.Insts.CoreCloneClone : core.clone.Clone JmpOp := {
  clone := JmpOp.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::JmpOp}]
    Source: 'src/lib.rs', lines 205:9-205:13 -/
@[reducible]
def JmpOp.Insts.CoreMarkerCopy : core.marker.Copy JmpOp := {
  cloneInst := JmpOp.Insts.CoreCloneClone
}

/-- [ebpf_validate::EndKind]
    Source: 'src/lib.rs', lines 223:0-227:1
    Visibility: public -/
@[discriminant isize]
inductive EndKind where
| Le : EndKind
| Be : EndKind
| Bswap : EndKind

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::EndKind}::clone]:
    Source: 'src/lib.rs', lines 221:15-221:20
    Visibility: public -/
def EndKind.Insts.CoreCloneClone.clone (self : EndKind) : Result EndKind := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::EndKind}]
    Source: 'src/lib.rs', lines 221:15-221:20 -/
@[reducible]
def EndKind.Insts.CoreCloneClone : core.clone.Clone EndKind := {
  clone := EndKind.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::EndKind}]
    Source: 'src/lib.rs', lines 221:9-221:13 -/
@[reducible]
def EndKind.Insts.CoreMarkerCopy : core.marker.Copy EndKind := {
  cloneInst := EndKind.Insts.CoreCloneClone
}

/-- [ebpf_validate::Op]
    Source: 'src/lib.rs', lines 234:0-246:1
    Visibility: public -/
@[discriminant isize]
inductive Op where
| Alu : AluWidth → AluOp → Source → Op
| End : EndKind → Op
| Load : Width → Bool → Op
| StoreImm : Width → Op
| StoreReg : Width → Op
| LoadImm64 : Op
| Atomic : Width → Op
| Ja : AluWidth → Op
| Jmp : AluWidth → JmpOp → Source → Op
| Call : Op
| Exit : Op

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Op}::clone]:
    Source: 'src/lib.rs', lines 232:15-232:20
    Visibility: public -/
def Op.Insts.CoreCloneClone.clone (self : Op) : Result Op := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Op}]
    Source: 'src/lib.rs', lines 232:15-232:20 -/
@[reducible]
def Op.Insts.CoreCloneClone : core.clone.Clone Op := {
  clone := Op.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::Op}]
    Source: 'src/lib.rs', lines 232:9-232:13 -/
@[reducible]
def Op.Insts.CoreMarkerCopy : core.marker.Copy Op := {
  cloneInst := Op.Insts.CoreCloneClone
}

/-- [ebpf_validate::width_from_size_bits]:
    Source: 'src/lib.rs', lines 248:0-260:1
    Visibility: public -/
def width_from_size_bits (bits : Std.U8) : Result (Option Width) := do
  if bits = SIZE_B
  then ok (some Width.B)
  else
    if bits = SIZE_H
    then ok (some Width.H)
    else
      if bits = SIZE_W
      then ok (some Width.W)
      else if bits = SIZE_DW
           then ok (some Width.DW)
           else ok none

/-- [ebpf_validate::alu_op_from_nibble]:
    Source: 'src/lib.rs', lines 262:0-292:1 -/
def alu_op_from_nibble (nibble : Std.U8) : Result (Option AluOp) := do
  if nibble = ALU_ADD
  then ok (some AluOp.Add)
  else
    if nibble = ALU_SUB
    then ok (some AluOp.Sub)
    else
      if nibble = ALU_MUL
      then ok (some AluOp.Mul)
      else
        if nibble = ALU_DIV
        then ok (some AluOp.Div)
        else
          if nibble = ALU_OR
          then ok (some AluOp.Or)
          else
            if nibble = ALU_AND
            then ok (some AluOp.And)
            else
              if nibble = ALU_LSH
              then ok (some AluOp.Lsh)
              else
                if nibble = ALU_RSH
                then ok (some AluOp.Rsh)
                else
                  if nibble = ALU_NEG
                  then ok (some AluOp.Neg)
                  else
                    if nibble = ALU_MOD
                    then ok (some AluOp.Mod)
                    else
                      if nibble = ALU_XOR
                      then ok (some AluOp.Xor)
                      else
                        if nibble = ALU_MOV
                        then ok (some AluOp.Mov)
                        else
                          if nibble = ALU_ARSH
                          then ok (some AluOp.Arsh)
                          else ok none

/-- [ebpf_validate::jmp_op_from_nibble]:
    Source: 'src/lib.rs', lines 294:0-320:1 -/
def jmp_op_from_nibble (nibble : Std.U8) : Result (Option JmpOp) := do
  if nibble = JMP_JEQ
  then ok (some JmpOp.Eq)
  else
    if nibble = JMP_JGT
    then ok (some JmpOp.Gt)
    else
      if nibble = JMP_JGE
      then ok (some JmpOp.Ge)
      else
        if nibble = JMP_JSET
        then ok (some JmpOp.Set)
        else
          if nibble = JMP_JNE
          then ok (some JmpOp.Ne)
          else
            if nibble = JMP_JSGT
            then ok (some JmpOp.Sgt)
            else
              if nibble = JMP_JSGE
              then ok (some JmpOp.Sge)
              else
                if nibble = JMP_JLT
                then ok (some JmpOp.Lt)
                else
                  if nibble = JMP_JLE
                  then ok (some JmpOp.Le)
                  else
                    if nibble = JMP_JSLT
                    then ok (some JmpOp.Slt)
                    else
                      if nibble = JMP_JSLE
                      then ok (some JmpOp.Sle)
                      else ok none

/-- [ebpf_validate::is_neg]:
    Source: 'src/lib.rs', lines 322:0-327:1 -/
def is_neg (op : AluOp) : Result Bool := do
  match op with
  | AluOp.Add => ok false
  | AluOp.Sub => ok false
  | AluOp.Mul => ok false
  | AluOp.Div => ok false
  | AluOp.Or => ok false
  | AluOp.And => ok false
  | AluOp.Lsh => ok false
  | AluOp.Rsh => ok false
  | AluOp.Neg => ok true
  | AluOp.Mod => ok false
  | AluOp.Xor => ok false
  | AluOp.Mov => ok false
  | AluOp.Arsh => ok false

/-- [ebpf_validate::is_reg]:
    Source: 'src/lib.rs', lines 329:0-334:1 -/
def is_reg (source : Source) : Result Bool := do
  match source with
  | Source.Imm => ok false
  | Source.Reg => ok true

/-- [ebpf_validate::is_w64]:
    Source: 'src/lib.rs', lines 336:0-341:1 -/
def is_w64 (width : AluWidth) : Result Bool := do
  match width with
  | AluWidth.W32 => ok false
  | AluWidth.W64 => ok true

/-- [ebpf_validate::is_w]:
    Source: 'src/lib.rs', lines 343:0-348:1 -/
def is_w (width : Width) : Result Bool := do
  match width with
  | Width.B => ok false
  | Width.H => ok false
  | Width.W => ok true
  | Width.DW => ok false

/-- [ebpf_validate::is_dw]:
    Source: 'src/lib.rs', lines 350:0-355:1 -/
def is_dw (width : Width) : Result Bool := do
  match width with
  | Width.B => ok false
  | Width.H => ok false
  | Width.W => ok false
  | Width.DW => ok true

/-- [ebpf_validate::decode]:
    Source: 'src/lib.rs', lines 359:0-468:1
    Visibility: public -/
def decode (opcode : Std.U8) : Result (Option Op) := do
  let i ← lift (opcode &&& SRC_REG)
  let source ← if i != 0#u8
                 then ok Source.Reg
                 else ok Source.Imm
  let cls ← lift (opcode &&& CLS_MASK)
  if cls = CLS_ALU
  then
    let width ← if cls = CLS_ALU64
                  then ok AluWidth.W64
                  else ok AluWidth.W32
    let i1 ← lift (opcode &&& ALU_MASK)
    if i1 = ALU_END
    then
      match width with
      | AluWidth.W32 =>
        match source with
        | Source.Imm => ok (some (Op.End EndKind.Le))
        | Source.Reg => ok (some (Op.End EndKind.Be))
      | AluWidth.W64 =>
        match source with
        | Source.Imm => ok (some (Op.End EndKind.Bswap))
        | Source.Reg => ok none
    else
      let i2 ← lift (opcode &&& ALU_MASK)
      let o ← alu_op_from_nibble i2
      match o with
      | none => ok none
      | some op =>
        let b ← is_neg op
        if b
        then
          let b1 ← is_reg source
          if b1
          then ok none
          else ok (some (Op.Alu width op source))
        else ok (some (Op.Alu width op source))
  else
    if cls = CLS_ALU64
    then
      let width ←
        if cls = CLS_ALU64
        then ok AluWidth.W64
        else ok AluWidth.W32
      let i1 ← lift (opcode &&& ALU_MASK)
      if i1 = ALU_END
      then
        match width with
        | AluWidth.W32 =>
          match source with
          | Source.Imm => ok (some (Op.End EndKind.Le))
          | Source.Reg => ok (some (Op.End EndKind.Be))
        | AluWidth.W64 =>
          match source with
          | Source.Imm => ok (some (Op.End EndKind.Bswap))
          | Source.Reg => ok none
      else
        let i2 ← lift (opcode &&& ALU_MASK)
        let o ← alu_op_from_nibble i2
        match o with
        | none => ok none
        | some op =>
          let b ← is_neg op
          if b
          then
            let b1 ← is_reg source
            if b1
            then ok none
            else ok (some (Op.Alu width op source))
          else ok (some (Op.Alu width op source))
    else
      if cls = CLS_LD
      then if opcode = OP_LDDW
           then ok (some Op.LoadImm64)
           else ok none
      else
        if cls = CLS_LDX
        then
          let i1 ← lift (opcode &&& SIZE_MASK)
          let o ← width_from_size_bits i1
          match o with
          | none => ok none
          | some width =>
            let mode ← lift (opcode &&& MODE_MASK)
            if mode = MODE_MEM
            then ok (some (Op.Load width false))
            else
              if mode = MODE_MEMSX
              then
                let b ← is_dw width
                if b
                then ok none
                else ok (some (Op.Load width true))
              else ok none
        else
          if cls = CLS_ST
          then
            let i1 ← lift (opcode &&& SIZE_MASK)
            let o ← width_from_size_bits i1
            match o with
            | none => ok none
            | some width =>
              let i2 ← lift (opcode &&& MODE_MASK)
              if i2 = MODE_MEM
              then ok (some (Op.StoreImm width))
              else ok none
          else
            if cls = CLS_STX
            then
              let i1 ← lift (opcode &&& SIZE_MASK)
              let o ← width_from_size_bits i1
              match o with
              | none => ok none
              | some width =>
                let mode ← lift (opcode &&& MODE_MASK)
                if mode = MODE_MEM
                then ok (some (Op.StoreReg width))
                else
                  if mode = MODE_ATOMIC
                  then
                    let b ← is_w width
                    if b
                    then ok (some (Op.Atomic width))
                    else
                      let b1 ← is_dw width
                      if b1
                      then ok (some (Op.Atomic width))
                      else ok none
                  else ok none
            else
              let width ←
                if cls = CLS_JMP32
                then ok AluWidth.W32
                else ok AluWidth.W64
              let nibble ← lift (opcode &&& JMP_MASK)
              if nibble = JMP_JA
              then
                let b ← is_reg source
                if b
                then ok none
                else ok (some (Op.Ja width))
              else
                if nibble = JMP_CALL
                then
                  let b ← is_w64 width
                  if b
                  then
                    let b1 ← is_reg source
                    if b1
                    then ok none
                    else ok (some Op.Call)
                  else ok none
                else
                  if nibble = JMP_EXIT
                  then
                    let b ← is_w64 width
                    if b
                    then
                      let b1 ← is_reg source
                      if b1
                      then ok none
                      else ok (some Op.Exit)
                    else ok none
                  else
                    let o ← jmp_op_from_nibble nibble
                    match o with
                    | none => ok none
                    | some op => ok (some (Op.Jmp width op source))

/-- [ebpf_validate::Filter]
    Source: 'src/lib.rs', lines 478:0-487:1
    Visibility: public -/
structure Filter where
  src_lo : Std.U8
  src_hi : Std.U8
  dst_lo : Std.U8
  dst_hi : Std.U8
  off_lo : Std.I16
  off_hi : Std.I16
  imm_lo : Std.I32
  imm_hi : Std.I32

/-- [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Filter}::clone]:
    Source: 'src/lib.rs', lines 476:15-476:20
    Visibility: public -/
def Filter.Insts.CoreCloneClone.clone (self : Filter) : Result Filter := do
  ok self

/-- Trait implementation: [ebpf_validate::{impl core::clone::Clone for ebpf_validate::Filter}]
    Source: 'src/lib.rs', lines 476:15-476:20 -/
@[reducible]
def Filter.Insts.CoreCloneClone : core.clone.Clone Filter := {
  clone := Filter.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [ebpf_validate::{impl core::marker::Copy for ebpf_validate::Filter}]
    Source: 'src/lib.rs', lines 476:9-476:13 -/
@[reducible]
def Filter.Insts.CoreMarkerCopy : core.marker.Copy Filter := {
  cloneInst := Filter.Insts.CoreCloneClone
}

/-- [ebpf_validate::filter]:
    Source: 'src/lib.rs', lines 489:0-500:1 -/
def filter
  (src : (Std.U8 × Std.U8)) (dst : (Std.U8 × Std.U8))
  (off : (Std.I16 × Std.I16)) (imm : (Std.I32 × Std.I32)) :
  Result Filter
  := do
  let (i, i1) := src
  let (i2, i3) := dst
  let (i4, i5) := off
  let (i6, i7) := imm
  ok
    {
      src_lo := i,
      src_hi := i1,
      dst_lo := i2,
      dst_hi := i3,
      off_lo := i4,
      off_hi := i5,
      imm_lo := i6,
      imm_hi := i7
    }

/-- [ebpf_validate::ANY_OFF]
    Source: 'src/lib.rs', lines 502:0-502:49 -/
@[global_simps, irreducible]
def ANY_OFF : (Std.I16 × Std.I16) := (core.num.I16.MIN, core.num.I16.MAX)

/-- [ebpf_validate::NO_OFF]
    Source: 'src/lib.rs', lines 503:0-503:34 -/
@[global_simps, irreducible]
def NO_OFF : (Std.I16 × Std.I16) := (0#i16, 0#i16)

/-- [ebpf_validate::ANY_IMM]
    Source: 'src/lib.rs', lines 504:0-504:49 -/
@[global_simps, irreducible]
def ANY_IMM : (Std.I32 × Std.I32) := (core.num.I32.MIN, core.num.I32.MAX)

/-- [ebpf_validate::NO_IMM]
    Source: 'src/lib.rs', lines 505:0-505:34 -/
@[global_simps, irreducible]
def NO_IMM : (Std.I32 × Std.I32) := (0#i32, 0#i32)

/-- [ebpf_validate::ALU_IMM]
    Source: 'src/lib.rs', lines 507:0-507:68
    Visibility: public -/
@[global_simps, irreducible]
def ALU_IMM : Result Filter := filter (0#u8, 0#u8) (0#u8, 9#u8) NO_OFF ANY_IMM

/-- [ebpf_validate::ALU_REG]
    Source: 'src/lib.rs', lines 508:0-508:68
    Visibility: public -/
@[global_simps, irreducible]
def ALU_REG : Result Filter := filter (0#u8, 10#u8) (0#u8, 9#u8) NO_OFF NO_IMM

/-- [ebpf_validate::DIV_IMM]
    Source: 'src/lib.rs', lines 509:0-509:68
    Visibility: public -/
@[global_simps, irreducible]
def DIV_IMM : Result Filter :=
  filter (0#u8, 0#u8) (0#u8, 9#u8) (0#i16, 1#i16) ANY_IMM

/-- [ebpf_validate::DIV_REG]
    Source: 'src/lib.rs', lines 510:0-510:68
    Visibility: public -/
@[global_simps, irreducible]
def DIV_REG : Result Filter :=
  filter (0#u8, 10#u8) (0#u8, 9#u8) (0#i16, 1#i16) NO_IMM

/-- [ebpf_validate::NEG]
    Source: 'src/lib.rs', lines 511:0-511:63
    Visibility: public -/
@[global_simps, irreducible]
def NEG : Result Filter := filter (0#u8, 0#u8) (0#u8, 9#u8) NO_OFF NO_IMM

/-- [ebpf_validate::ENDIAN]
    Source: 'src/lib.rs', lines 512:0-512:67
    Visibility: public -/
@[global_simps, irreducible]
def ENDIAN : Result Filter :=
  filter (0#u8, 0#u8) (0#u8, 9#u8) NO_OFF (0#i32, 64#i32)

/-- [ebpf_validate::MOVSX]
    Source: 'src/lib.rs', lines 515:0-515:34
    Visibility: public -/
@[global_simps, irreducible] def MOVSX : Result Filter := ALU_REG

/-- [ebpf_validate::LDX]
    Source: 'src/lib.rs', lines 516:0-516:65
    Visibility: public -/
@[global_simps, irreducible]
def LDX : Result Filter := filter (0#u8, 10#u8) (0#u8, 9#u8) ANY_OFF NO_IMM

/-- [ebpf_validate::ST]
    Source: 'src/lib.rs', lines 517:0-517:65
    Visibility: public -/
@[global_simps, irreducible]
def ST : Result Filter := filter (0#u8, 0#u8) (0#u8, 10#u8) ANY_OFF ANY_IMM

/-- [ebpf_validate::STX]
    Source: 'src/lib.rs', lines 518:0-518:66
    Visibility: public -/
@[global_simps, irreducible]
def STX : Result Filter := filter (0#u8, 10#u8) (0#u8, 10#u8) ANY_OFF NO_IMM

/-- [ebpf_validate::LDDW]
    Source: 'src/lib.rs', lines 519:0-519:65
    Visibility: public -/
@[global_simps, irreducible]
def LDDW : Result Filter := filter (0#u8, 6#u8) (0#u8, 9#u8) NO_OFF ANY_IMM

/-- [ebpf_validate::LDDW_HIGH]
    Source: 'src/lib.rs', lines 520:0-520:70
    Visibility: public -/
@[global_simps, irreducible]
def LDDW_HIGH : Result Filter :=
  filter (0#u8, 0#u8) (0#u8, 0#u8) NO_OFF ANY_IMM

/-- [ebpf_validate::JA]
    Source: 'src/lib.rs', lines 521:0-521:63
    Visibility: public -/
@[global_simps, irreducible]
def JA : Result Filter := filter (0#u8, 0#u8) (0#u8, 0#u8) ANY_OFF NO_IMM

/-- [ebpf_validate::JA32]
    Source: 'src/lib.rs', lines 522:0-522:65
    Visibility: public -/
@[global_simps, irreducible]
def JA32 : Result Filter := filter (0#u8, 0#u8) (0#u8, 0#u8) NO_OFF ANY_IMM

/-- [ebpf_validate::JMP_IMM]
    Source: 'src/lib.rs', lines 523:0-523:69
    Visibility: public -/
@[global_simps, irreducible]
def JMP_IMM : Result Filter := filter (0#u8, 0#u8) (0#u8, 9#u8) ANY_OFF ANY_IMM

/-- [ebpf_validate::JMP_REG]
    Source: 'src/lib.rs', lines 524:0-524:69
    Visibility: public -/
@[global_simps, irreducible]
def JMP_REG : Result Filter := filter (0#u8, 10#u8) (0#u8, 9#u8) ANY_OFF NO_IMM

/-- [ebpf_validate::CALL]
    Source: 'src/lib.rs', lines 525:0-525:65
    Visibility: public -/
@[global_simps, irreducible]
def CALL : Result Filter := filter (0#u8, 2#u8) (0#u8, 0#u8) NO_OFF ANY_IMM

/-- [ebpf_validate::EXIT]
    Source: 'src/lib.rs', lines 526:0-526:64
    Visibility: public -/
@[global_simps, irreducible]
def EXIT : Result Filter := filter (0#u8, 0#u8) (0#u8, 0#u8) NO_OFF NO_IMM

/-- [ebpf_validate::ATOMIC32]
    Source: 'src/lib.rs', lines 527:0-527:72
    Visibility: public -/
@[global_simps, irreducible]
def ATOMIC32 : Result Filter :=
  filter (0#u8, 9#u8) (0#u8, 10#u8) ANY_OFF (0#i32, 255#i32)

/-- [ebpf_validate::ATOMIC64]
    Source: 'src/lib.rs', lines 530:0-530:70
    Visibility: public -/
@[global_simps, irreducible]
def ATOMIC64 : Result Filter :=
  filter (0#u8, 9#u8) (0#u8, 10#u8) ANY_OFF NO_IMM

/-- [ebpf_validate::filter_for]:
    Source: 'src/lib.rs', lines 534:0-562:1
    Visibility: public -/
def filter_for (opcode : Std.U8) : Result (Option Filter) := do
  match opcode with
  | 4#uscalar => let f ← ALU_IMM
                 ok (some f)
  | 20#uscalar => let f ← ALU_IMM
                  ok (some f)
  | 36#uscalar => let f ← ALU_IMM
                  ok (some f)
  | 68#uscalar => let f ← ALU_IMM
                  ok (some f)
  | 84#uscalar => let f ← ALU_IMM
                  ok (some f)
  | 100#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 116#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 164#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 180#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 196#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 7#uscalar => let f ← ALU_IMM
                 ok (some f)
  | 23#uscalar => let f ← ALU_IMM
                  ok (some f)
  | 39#uscalar => let f ← ALU_IMM
                  ok (some f)
  | 71#uscalar => let f ← ALU_IMM
                  ok (some f)
  | 87#uscalar => let f ← ALU_IMM
                  ok (some f)
  | 103#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 119#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 167#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 183#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 199#uscalar => let f ← ALU_IMM
                   ok (some f)
  | 12#uscalar => let f ← ALU_REG
                  ok (some f)
  | 28#uscalar => let f ← ALU_REG
                  ok (some f)
  | 44#uscalar => let f ← ALU_REG
                  ok (some f)
  | 76#uscalar => let f ← ALU_REG
                  ok (some f)
  | 92#uscalar => let f ← ALU_REG
                  ok (some f)
  | 108#uscalar => let f ← ALU_REG
                   ok (some f)
  | 124#uscalar => let f ← ALU_REG
                   ok (some f)
  | 172#uscalar => let f ← ALU_REG
                   ok (some f)
  | 204#uscalar => let f ← ALU_REG
                   ok (some f)
  | 15#uscalar => let f ← ALU_REG
                  ok (some f)
  | 31#uscalar => let f ← ALU_REG
                  ok (some f)
  | 47#uscalar => let f ← ALU_REG
                  ok (some f)
  | 79#uscalar => let f ← ALU_REG
                  ok (some f)
  | 95#uscalar => let f ← ALU_REG
                  ok (some f)
  | 111#uscalar => let f ← ALU_REG
                   ok (some f)
  | 127#uscalar => let f ← ALU_REG
                   ok (some f)
  | 175#uscalar => let f ← ALU_REG
                   ok (some f)
  | 207#uscalar => let f ← ALU_REG
                   ok (some f)
  | 52#uscalar => let f ← DIV_IMM
                  ok (some f)
  | 148#uscalar => let f ← DIV_IMM
                   ok (some f)
  | 55#uscalar => let f ← DIV_IMM
                  ok (some f)
  | 151#uscalar => let f ← DIV_IMM
                   ok (some f)
  | 60#uscalar => let f ← DIV_REG
                  ok (some f)
  | 156#uscalar => let f ← DIV_REG
                   ok (some f)
  | 63#uscalar => let f ← DIV_REG
                  ok (some f)
  | 159#uscalar => let f ← DIV_REG
                   ok (some f)
  | 132#uscalar => let f ← NEG
                   ok (some f)
  | 135#uscalar => let f ← NEG
                   ok (some f)
  | 212#uscalar => let f ← ENDIAN
                   ok (some f)
  | 215#uscalar => let f ← ENDIAN
                   ok (some f)
  | 220#uscalar => let f ← ENDIAN
                   ok (some f)
  | 188#uscalar => let f ← MOVSX
                   ok (some f)
  | 191#uscalar => let f ← MOVSX
                   ok (some f)
  | 97#uscalar => let f ← LDX
                  ok (some f)
  | 105#uscalar => let f ← LDX
                   ok (some f)
  | 113#uscalar => let f ← LDX
                   ok (some f)
  | 121#uscalar => let f ← LDX
                   ok (some f)
  | 129#uscalar => let f ← LDX
                   ok (some f)
  | 137#uscalar => let f ← LDX
                   ok (some f)
  | 145#uscalar => let f ← LDX
                   ok (some f)
  | 98#uscalar => let f ← ST
                  ok (some f)
  | 106#uscalar => let f ← ST
                   ok (some f)
  | 114#uscalar => let f ← ST
                   ok (some f)
  | 122#uscalar => let f ← ST
                   ok (some f)
  | 99#uscalar => let f ← STX
                  ok (some f)
  | 107#uscalar => let f ← STX
                   ok (some f)
  | 115#uscalar => let f ← STX
                   ok (some f)
  | 123#uscalar => let f ← STX
                   ok (some f)
  | 24#uscalar => let f ← LDDW
                  ok (some f)
  | 0#uscalar => let f ← LDDW_HIGH
                 ok (some f)
  | 5#uscalar => let f ← JA
                 ok (some f)
  | 6#uscalar => let f ← JA32
                 ok (some f)
  | 21#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 37#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 53#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 69#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 85#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 101#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 117#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 165#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 181#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 197#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 213#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 22#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 38#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 54#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 70#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 86#uscalar => let f ← JMP_IMM
                  ok (some f)
  | 102#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 118#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 166#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 182#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 198#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 214#uscalar => let f ← JMP_IMM
                   ok (some f)
  | 29#uscalar => let f ← JMP_REG
                  ok (some f)
  | 45#uscalar => let f ← JMP_REG
                  ok (some f)
  | 61#uscalar => let f ← JMP_REG
                  ok (some f)
  | 77#uscalar => let f ← JMP_REG
                  ok (some f)
  | 93#uscalar => let f ← JMP_REG
                  ok (some f)
  | 109#uscalar => let f ← JMP_REG
                   ok (some f)
  | 125#uscalar => let f ← JMP_REG
                   ok (some f)
  | 173#uscalar => let f ← JMP_REG
                   ok (some f)
  | 189#uscalar => let f ← JMP_REG
                   ok (some f)
  | 205#uscalar => let f ← JMP_REG
                   ok (some f)
  | 221#uscalar => let f ← JMP_REG
                   ok (some f)
  | 30#uscalar => let f ← JMP_REG
                  ok (some f)
  | 46#uscalar => let f ← JMP_REG
                  ok (some f)
  | 62#uscalar => let f ← JMP_REG
                  ok (some f)
  | 78#uscalar => let f ← JMP_REG
                  ok (some f)
  | 94#uscalar => let f ← JMP_REG
                  ok (some f)
  | 110#uscalar => let f ← JMP_REG
                   ok (some f)
  | 126#uscalar => let f ← JMP_REG
                   ok (some f)
  | 174#uscalar => let f ← JMP_REG
                   ok (some f)
  | 190#uscalar => let f ← JMP_REG
                   ok (some f)
  | 206#uscalar => let f ← JMP_REG
                   ok (some f)
  | 222#uscalar => let f ← JMP_REG
                   ok (some f)
  | 133#uscalar => let f ← CALL
                   ok (some f)
  | 149#uscalar => let f ← EXIT
                   ok (some f)
  | 195#uscalar => let f ← ATOMIC32
                   ok (some f)
  | 219#uscalar => let f ← ATOMIC64
                   ok (some f)
  | _ => ok none

/-- [ebpf_validate::offset_ok]:
    Source: 'src/lib.rs', lines 566:0-574:1
    Visibility: public -/
def offset_ok
  (opcode : Std.U8) (f : Filter) (offset : Std.I16) : Result Bool := do
  if opcode = 188#u8
  then
    if offset = 0#i16
    then ok true
    else if offset = 8#i16
         then ok true
         else ok (offset = 16#i16)
  else
    if opcode = 191#u8
    then
      if offset = 0#i16
      then ok true
      else
        if offset = 8#i16
        then ok true
        else if offset = 16#i16
             then ok true
             else ok (offset = 32#i16)
    else if offset >= f.off_lo
         then ok (offset <= f.off_hi)
         else ok false

/-- [ebpf_validate::imm_ok]:
    Source: 'src/lib.rs', lines 578:0-593:1
    Visibility: public -/
def imm_ok (opcode : Std.U8) (f : Filter) (imm : Std.I32) : Result Bool := do
  if opcode = 219#u8
  then
    if imm = 0#i32
    then ok true
    else
      if imm = 1#i32
      then ok true
      else
        if imm = 64#i32
        then ok true
        else
          if imm = 65#i32
          then ok true
          else
            if imm = 80#i32
            then ok true
            else
              if imm = 81#i32
              then ok true
              else
                if imm = 160#i32
                then ok true
                else
                  if imm = 161#i32
                  then ok true
                  else if imm = 225#i32
                       then ok true
                       else ok (imm = 241#i32)
  else if imm >= f.imm_lo
       then ok (imm <= f.imm_hi)
       else ok false

/-- [ebpf_validate::check_operand_filter]:
    Source: 'src/lib.rs', lines 597:0-614:1
    Visibility: public -/
def check_operand_filter
  (insn : Insn) (pc : Std.Usize) :
  Result (core.result.Result Unit Reject)
  := do
  let o ← filter_for insn.opcode
  match o with
  | none => ok (core.result.Result.Err (Reject.FilterOpcode pc))
  | some f =>
    if insn.dst < f.dst_lo
    then ok (core.result.Result.Err (Reject.FilterDst pc))
    else
      if insn.dst > f.dst_hi
      then ok (core.result.Result.Err (Reject.FilterDst pc))
      else
        if insn.src < f.src_lo
        then ok (core.result.Result.Err (Reject.FilterSrc pc))
        else
          if insn.src > f.src_hi
          then ok (core.result.Result.Err (Reject.FilterSrc pc))
          else
            let b ← imm_ok insn.opcode f insn.imm
            if b
            then
              let b1 ← offset_ok insn.opcode f insn.offset
              if b1
              then ok (core.result.Result.Ok ())
              else ok (core.result.Result.Err (Reject.FilterOffset pc))
            else ok (core.result.Result.Err (Reject.FilterImm pc))

/-- [ebpf_validate::check_atomic_selector]:
    Source: 'src/lib.rs', lines 621:0-634:1
    Visibility: public -/
def check_atomic_selector
  (insn : Insn) (pc : Std.Usize) :
  Result (core.result.Result Unit Reject)
  := do
  let i ← lift (insn.imm &&& ATOMIC_OP_FETCH)
  let i1 ← lift (UScalar.hcast .I32 ALU_MASK)
  let op ← lift (insn.imm &&& i1)
  let i2 ← lift (UScalar.hcast .I32 ALU_ADD)
  if op = i2
  then ok (core.result.Result.Ok ())
  else
    let i3 ← lift (UScalar.hcast .I32 ALU_OR)
    if op = i3
    then ok (core.result.Result.Ok ())
    else
      let i4 ← lift (UScalar.hcast .I32 ALU_AND)
      if op = i4
      then ok (core.result.Result.Ok ())
      else
        let i5 ← lift (UScalar.hcast .I32 ALU_XOR)
        if op = i5
        then ok (core.result.Result.Ok ())
        else
          let i6 ← lift (~~~ ATOMIC_OP_FETCH)
          let i7 ← lift (ATOMIC_OP_XCHG &&& i6)
          if op = i7
          then
            if i != 0#i32
            then ok (core.result.Result.Ok ())
            else ok (core.result.Result.Err (Reject.AtomicNeedsFetch pc))
          else
            let i8 ← lift (~~~ ATOMIC_OP_FETCH)
            let i9 ← lift (ATOMIC_OP_CMPXCHG &&& i8)
            if op = i9
            then
              if i != 0#i32
              then ok (core.result.Result.Ok ())
              else ok (core.result.Result.Err (Reject.AtomicNeedsFetch pc))
            else ok (core.result.Result.Err (Reject.AtomicUnknown pc))

/-- [ebpf_validate::helper_known]: loop body 0:
    Source: 'src/lib.rs', lines 645:2-652:1 -/
@[rust_loop_body]
def helper_known_loop.body
  (known_helpers : Slice Std.U32) (index : Std.U32) (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len known_helpers
  if k < i
  then
    let i1 ← Slice.index_usize known_helpers k
    if i1 = index
    then ok (done true)
    else let k1 ← k + 1#usize
         ok (cont k1)
  else ok (done false)

/-- [ebpf_validate::helper_known]: loop 0:
    Source: 'src/lib.rs', lines 645:2-652:1 -/
@[rust_loop]
def helper_known_loop
  (known_helpers : Slice Std.U32) (index : Std.U32) (k : Std.Usize) :
  Result Bool
  := do
  loop
    (fun k1 => helper_known_loop.body known_helpers index k1)
    k

/-- [ebpf_validate::helper_known]:
    Source: 'src/lib.rs', lines 637:0-652:1 -/
def helper_known
  (config : Config) (known_helpers : Slice Std.U32) (index : Std.U32) :
  Result Bool
  := do
  if config.has_dispatcher
  then
    if config.accept_every_helper
    then ok true
    else helper_known_loop known_helpers index 0#usize
  else ok false

/-- [ebpf_validate::check_call]:
    Source: 'src/lib.rs', lines 655:0-693:1
    Visibility: public -/
def check_call
  (config : Config) (known_helpers : Slice Std.U32) (insn : Insn)
  (insns : Slice Insn) (pc : Std.Usize) (cross_section : Bool) :
  Result (core.result.Result Unit Reject)
  := do
  let num_insns := Slice.len insns
  if cross_section
  then
    if insn.src != 2#u8
    then ok (core.result.Result.Err (Reject.CrossSectionMetadata pc))
    else
      if insn.src = 0#u8
      then
        if insn.imm < 0#i32
        then ok (core.result.Result.Err (Reject.HelperImm pc))
        else
          let i ← lift (IScalar.hcast .U32 insn.imm)
          let b ← helper_known config known_helpers i
          if b
          then ok (core.result.Result.Ok ())
          else ok (core.result.Result.Err (Reject.UnknownHelper pc))
      else
        if insn.src = 1#u8
        then
          let i ← lift (UScalar.hcast .I64 pc)
          let i1 ← i + 1#i64
          let i2 ← lift (IScalar.cast .I64 insn.imm)
          let target ← i1 + i2
          if target < 0#i64
          then ok (core.result.Result.Err (Reject.LocalCallOutOfBounds pc))
          else
            let i3 ← lift (UScalar.hcast .I64 num_insns)
            if target >= i3
            then ok (core.result.Result.Err (Reject.LocalCallOutOfBounds pc))
            else
              let i4 ← lift (IScalar.hcast .Usize target)
              let i5 ← Slice.index_usize insns i4
              if i5.opcode = 0#u8
              then ok (core.result.Result.Err (Reject.CallIntoLddw pc))
              else ok (core.result.Result.Ok ())
        else
          if insn.src = 2#u8
          then ok (core.result.Result.Ok ())
          else ok (core.result.Result.Err (Reject.CallType pc))
  else
    if insn.src = 0#u8
    then
      if insn.imm < 0#i32
      then ok (core.result.Result.Err (Reject.HelperImm pc))
      else
        let i ← lift (IScalar.hcast .U32 insn.imm)
        let b ← helper_known config known_helpers i
        if b
        then ok (core.result.Result.Ok ())
        else ok (core.result.Result.Err (Reject.UnknownHelper pc))
    else
      if insn.src = 1#u8
      then
        let i ← lift (UScalar.hcast .I64 pc)
        let i1 ← i + 1#i64
        let i2 ← lift (IScalar.cast .I64 insn.imm)
        let target ← i1 + i2
        if target < 0#i64
        then ok (core.result.Result.Err (Reject.LocalCallOutOfBounds pc))
        else
          let i3 ← lift (UScalar.hcast .I64 num_insns)
          if target >= i3
          then ok (core.result.Result.Err (Reject.LocalCallOutOfBounds pc))
          else
            let i4 ← lift (IScalar.hcast .Usize target)
            let i5 ← Slice.index_usize insns i4
            if i5.opcode = 0#u8
            then ok (core.result.Result.Err (Reject.CallIntoLddw pc))
            else ok (core.result.Result.Ok ())
      else
        if insn.src = 2#u8
        then ok (core.result.Result.Err (Reject.BtfCall pc))
        else ok (core.result.Result.Err (Reject.CallType pc))

/-- [ebpf_validate::is_store_form]:
    Source: 'src/lib.rs', lines 700:0-705:1
    Visibility: public -/
def is_store_form (op : Op) : Result Bool := do
  match op with
  | Op.Alu _ _ _ => ok false
  | Op.End _ => ok false
  | Op.Load _ _ => ok false
  | Op.StoreImm _ => ok true
  | Op.StoreReg _ => ok true
  | Op.LoadImm64 => ok false
  | Op.Atomic _ => ok true
  | Op.Ja _ => ok false
  | Op.Jmp _ _ _ => ok false
  | Op.Call => ok false
  | Op.Exit => ok false

/-- [ebpf_validate::is_load_imm64]:
    Source: 'src/lib.rs', lines 708:0-713:1
    Visibility: public -/
def is_load_imm64 (op : Op) : Result Bool := do
  match op with
  | Op.Alu _ _ _ => ok false
  | Op.End _ => ok false
  | Op.Load _ _ => ok false
  | Op.StoreImm _ => ok false
  | Op.StoreReg _ => ok false
  | Op.LoadImm64 => ok true
  | Op.Atomic _ => ok false
  | Op.Ja _ => ok false
  | Op.Jmp _ _ _ => ok false
  | Op.Call => ok false
  | Op.Exit => ok false

/-- [ebpf_validate::check_structure]:
    Source: 'src/lib.rs', lines 717:0-782:1
    Visibility: public -/
def check_structure
  (config : Config) (known_helpers : Slice Std.U32) (insns : Slice Insn)
  (external_calls : Slice Bool) (pc : Std.Usize) (insn : Insn) (op : Op) :
  Result (core.result.Result Unit Reject)
  := do
  let num_insns := Slice.len insns
  match op with
  | Op.Alu _ ao _ =>
    match ao with
    | AluOp.Add => ok (core.result.Result.Ok ())
    | AluOp.Sub => ok (core.result.Result.Ok ())
    | AluOp.Mul => ok (core.result.Result.Ok ())
    | AluOp.Div => ok (core.result.Result.Ok ())
    | AluOp.Or => ok (core.result.Result.Ok ())
    | AluOp.And => ok (core.result.Result.Ok ())
    | AluOp.Lsh => ok (core.result.Result.Ok ())
    | AluOp.Rsh => ok (core.result.Result.Ok ())
    | AluOp.Neg =>
      if insn.src != 0#u8
      then ok (core.result.Result.Err (Reject.NegSrc pc))
      else ok (core.result.Result.Ok ())
    | AluOp.Mod => ok (core.result.Result.Ok ())
    | AluOp.Xor => ok (core.result.Result.Ok ())
    | AluOp.Mov => ok (core.result.Result.Ok ())
    | AluOp.Arsh => ok (core.result.Result.Ok ())
  | Op.End _ =>
    if insn.imm != 16#i32
    then
      if insn.imm != 32#i32
      then
        if insn.imm != 64#i32
        then ok (core.result.Result.Err (Reject.EndianImm pc))
        else ok (core.result.Result.Ok ())
      else ok (core.result.Result.Ok ())
    else ok (core.result.Result.Ok ())
  | Op.Load _ _ => ok (core.result.Result.Ok ())
  | Op.StoreImm _ => ok (core.result.Result.Ok ())
  | Op.StoreReg _ => ok (core.result.Result.Ok ())
  | Op.LoadImm64 =>
    if insn.src != 0#u8
    then ok (core.result.Result.Err (Reject.LddwSrc pc))
    else
      let i ← pc + 1#usize
      if i >= num_insns
      then ok (core.result.Result.Err (Reject.IncompleteLddw pc))
      else
        let i1 ← Slice.index_usize insns i
        if i1.opcode != 0#u8
        then ok (core.result.Result.Err (Reject.IncompleteLddw pc))
        else
          let high ← Slice.index_usize insns i
          if high.dst != 0#u8
          then ok (core.result.Result.Err (Reject.LddwSecondHalf i))
          else
            if high.src != 0#u8
            then ok (core.result.Result.Err (Reject.LddwSecondHalf i))
            else
              if high.offset != 0#i16
              then ok (core.result.Result.Err (Reject.LddwSecondHalf i))
              else ok (core.result.Result.Ok ())
  | Op.Atomic _ => check_atomic_selector insn pc
  | Op.Ja _ =>
    let displacement ←
      if insn.opcode = OP_JA32
      then ok insn.imm
      else ok (IScalar.cast .I32 insn.offset)
    if displacement = (-1)#i32
    then ok (core.result.Result.Err (Reject.InfiniteLoop pc))
    else
      let i ← lift (UScalar.hcast .I64 pc)
      let i1 ← i + 1#i64
      let i2 ← lift (IScalar.cast .I64 displacement)
      let target ← i1 + i2
      if target < 0#i64
      then ok (core.result.Result.Err (Reject.JumpOutOfBounds pc))
      else
        let i3 ← lift (UScalar.hcast .I64 num_insns)
        if target >= i3
        then ok (core.result.Result.Err (Reject.JumpOutOfBounds pc))
        else
          let i4 ← lift (IScalar.hcast .Usize target)
          let i5 ← Slice.index_usize insns i4
          if i5.opcode = 0#u8
          then ok (core.result.Result.Err (Reject.JumpIntoLddw pc))
          else ok (core.result.Result.Ok ())
  | Op.Jmp _ _ _ =>
    let displacement ←
      if insn.opcode = OP_JA32
      then ok insn.imm
      else ok (IScalar.cast .I32 insn.offset)
    if displacement = (-1)#i32
    then ok (core.result.Result.Err (Reject.InfiniteLoop pc))
    else
      let i ← lift (UScalar.hcast .I64 pc)
      let i1 ← i + 1#i64
      let i2 ← lift (IScalar.cast .I64 displacement)
      let target ← i1 + i2
      if target < 0#i64
      then ok (core.result.Result.Err (Reject.JumpOutOfBounds pc))
      else
        let i3 ← lift (UScalar.hcast .I64 num_insns)
        if target >= i3
        then ok (core.result.Result.Err (Reject.JumpOutOfBounds pc))
        else
          let i4 ← lift (IScalar.hcast .Usize target)
          let i5 ← Slice.index_usize insns i4
          if i5.opcode = 0#u8
          then ok (core.result.Result.Err (Reject.JumpIntoLddw pc))
          else ok (core.result.Result.Ok ())
  | Op.Call =>
    let i := Slice.len external_calls
    let cross_section ←
      if pc < i
      then Slice.index_usize external_calls pc
      else ok false
    check_call config known_helpers insn insns pc cross_section
  | Op.Exit => ok (core.result.Result.Ok ())

/-- [ebpf_validate::check_slot]:
    Source: 'src/lib.rs', lines 786:0-812:1
    Visibility: public -/
def check_slot
  (config : Config) (known_helpers : Slice Std.U32) (insns : Slice Insn)
  (external_calls : Slice Bool) (pc : Std.Usize) :
  Result (core.result.Result Bool Reject)
  := do
  let insn ← Slice.index_usize insns pc
  let o ← decode insn.opcode
  match o with
  | none => ok (core.result.Result.Err (Reject.UnknownOpcode pc))
  | some op =>
    let r ←
      check_structure config known_helpers insns external_calls pc insn op
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      if insn.src > 10#u8
      then ok (core.result.Result.Err (Reject.InvalidSrc pc))
      else
        if insn.dst > 9#u8
        then
          let b ← is_store_form op
          if b
          then
            if insn.dst = 10#u8
            then
              let r1 ← check_operand_filter insn pc
              let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
              match cf1 with
              | core.ops.control_flow.ControlFlow.Continue _ =>
                let b1 ← is_load_imm64 op
                ok (core.result.Result.Ok b1)
              | core.ops.control_flow.ControlFlow.Break residual =>
                core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
                  Bool (core.convert.FromSame Reject) residual
            else ok (core.result.Result.Err (Reject.InvalidDst pc))
          else ok (core.result.Result.Err (Reject.InvalidDst pc))
        else
          let r1 ← check_operand_filter insn pc
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue _ =>
            let b ← is_load_imm64 op
            ok (core.result.Result.Ok b)
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
              Bool (core.convert.FromSame Reject) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Bool (core.convert.FromSame Reject) residual

/-- [ebpf_validate::is_unconditional_jump]:
    Source: 'src/lib.rs', lines 841:0-843:1 -/
def is_unconditional_jump (insn : Insn) : Result Bool := do
  if insn.opcode = OP_JA
  then ok true
  else ok (insn.opcode = OP_JA32)

/-- [ebpf_validate::check_sub_program]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-903:1 -/
@[rust_loop_body]
def check_sub_program_loop.body
  (insns : Slice Insn) (start : Std.Usize) («end» : Std.Usize)
  (j : Std.Usize) :
  Result (ControlFlow Std.Usize (core.result.Result Unit Reject))
  := do
  if j < «end»
  then
    let insn ← Slice.index_usize insns j
    let cls ← lift (insn.opcode &&& CLS_MASK)
    if cls = CLS_JMP
    then
      if insn.opcode != OP_CALL
      then
        if insn.opcode != OP_EXIT
        then
          let displacement ←
            if insn.opcode = OP_JA32
            then ok (IScalar.cast .I64 insn.imm)
            else ok (IScalar.cast .I64 insn.offset)
          let i ← lift (UScalar.hcast .I64 j)
          let i1 ← i + 1#i64
          let target ← i1 + displacement
          let i2 ← lift (UScalar.hcast .I64 start)
          if target < i2
          then ok (done (core.result.Result.Err (Reject.SubProgramJump j)))
          else
            let i3 ← lift (UScalar.hcast .I64 «end»)
            let i4 ← i3 - 1#i64
            if target > i4
            then ok (done (core.result.Result.Err (Reject.SubProgramJump j)))
            else let j1 ← j + 1#usize
                 ok (cont j1)
        else let j1 ← j + 1#usize
             ok (cont j1)
      else let j1 ← j + 1#usize
           ok (cont j1)
    else
      if cls = CLS_JMP32
      then
        if insn.opcode != OP_CALL
        then
          if insn.opcode != OP_EXIT
          then
            let displacement ←
              if insn.opcode = OP_JA32
              then ok (IScalar.cast .I64 insn.imm)
              else ok (IScalar.cast .I64 insn.offset)
            let i ← lift (UScalar.hcast .I64 j)
            let i1 ← i + 1#i64
            let target ← i1 + displacement
            let i2 ← lift (UScalar.hcast .I64 start)
            if target < i2
            then ok (done (core.result.Result.Err (Reject.SubProgramJump j)))
            else
              let i3 ← lift (UScalar.hcast .I64 «end»)
              let i4 ← i3 - 1#i64
              if target > i4
              then ok (done (core.result.Result.Err (Reject.SubProgramJump j)))
              else let j1 ← j + 1#usize
                   ok (cont j1)
          else let j1 ← j + 1#usize
               ok (cont j1)
        else let j1 ← j + 1#usize
             ok (cont j1)
      else let j1 ← j + 1#usize
           ok (cont j1)
  else
    let i ← «end» - 1#usize
    let i1 ← Slice.index_usize insns i
    let i2 ← Slice.index_usize insns i
    let b ← is_unconditional_jump i2
    let ends_with_jump ←
      if b
      then ok true
      else
        do
        let i3 ← start + 2#usize
        if «end» >= i3
        then
          let i4 ← «end» - 2#usize
          let i5 ← Slice.index_usize insns i4
          is_unconditional_jump i5
        else ok false
    if i1.opcode = OP_EXIT
    then ok (done (core.result.Result.Ok ()))
    else
      if ends_with_jump
      then ok (done (core.result.Result.Ok ()))
      else ok (done (core.result.Result.Err (Reject.SubProgramEnd i)))

/-- [ebpf_validate::check_sub_program]: loop 0:
    Source: 'src/lib.rs', lines 1:0-903:1 -/
@[rust_loop]
def check_sub_program_loop
  (insns : Slice Insn) (start : Std.Usize) («end» : Std.Usize)
  (j : Std.Usize) :
  Result (core.result.Result Unit Reject)
  := do
  loop
    (fun j1 => check_sub_program_loop.body insns start «end» j1)
    j

/-- [ebpf_validate::check_sub_program]:
    Source: 'src/lib.rs', lines 877:0-903:1 -/
@[reducible]
def check_sub_program
  (insns : Slice Insn) (start : Std.Usize) («end» : Std.Usize) :
  Result (core.result.Result Unit Reject)
  := do
  check_sub_program_loop insns start «end» start

/-- [ebpf_validate::sub_program_end]: loop body 0:
    Source: 'src/lib.rs', lines 866:2-873:1 -/
@[rust_loop_body]
def sub_program_end_loop.body
  (is_start : Slice Bool) («end» : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := Slice.len is_start
  if «end» < i
  then
    let b ← Slice.index_usize is_start «end»
    if b
    then ok (done «end»)
    else let end1 ← «end» + 1#usize
         ok (cont end1)
  else let end1 := Slice.len is_start
       ok (done end1)

/-- [ebpf_validate::sub_program_end]: loop 0:
    Source: 'src/lib.rs', lines 866:2-873:1 -/
@[rust_loop]
def sub_program_end_loop
  (is_start : Slice Bool) («end» : Std.Usize) : Result Std.Usize := do
  loop
    (fun end1 => sub_program_end_loop.body is_start end1)
    «end»

/-- [ebpf_validate::sub_program_end]:
    Source: 'src/lib.rs', lines 864:0-873:1 -/
def sub_program_end
  (is_start : Slice Bool) (start : Std.Usize) : Result Std.Usize := do
  let «end» ← start + 1#usize
  sub_program_end_loop is_start «end»

/-- [ebpf_validate::is_local_call]:
    Source: 'src/lib.rs', lines 837:0-839:1 -/
def is_local_call (insn : Insn) : Result Bool := do
  if insn.opcode = OP_CALL
  then ok (insn.src = 1#u8)
  else ok false

/-- [ebpf_validate::mark_sub_program_starts]: loop body 0:
    Source: 'src/lib.rs', lines 850:2-858:3 -/
@[rust_loop_body]
def mark_sub_program_starts_loop.body
  (insns : Slice Insn) (is_start : alloc.vec.Vec Bool) (any : Bool)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Bool) × Bool × Std.Usize) (Bool ×
    (alloc.vec.Vec Bool)))
  := do
  let i1 := Slice.len insns
  if i < i1
  then
    let i2 ← Slice.index_usize insns i
    let b ← is_local_call i2
    let (is_start1, any1) ←
      if b
      then
        do
        let i3 ← lift (UScalar.hcast .I64 i)
        let i4 ← i3 + 1#i64
        let i5 ← lift (IScalar.cast .I64 i2.imm)
        let i6 ← i4 + i5
        let target ← lift (IScalar.hcast .Usize i6)
        let (_, index_mut_back) ←
          alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Bool)
            is_start target
        let is_start2 := index_mut_back true
        ok (is_start2, true)
      else ok (is_start, any)
    let i3 ← i + 1#usize
    ok (cont (is_start1, any1, i3))
  else ok (done (any, is_start))

/-- [ebpf_validate::mark_sub_program_starts]: loop 0:
    Source: 'src/lib.rs', lines 850:2-858:3 -/
@[rust_loop]
def mark_sub_program_starts_loop
  (insns : Slice Insn) (is_start : alloc.vec.Vec Bool) (any : Bool)
  (i : Std.Usize) :
  Result (Bool × (alloc.vec.Vec Bool))
  := do
  loop
    (fun (is_start1, any1, i1) => mark_sub_program_starts_loop.body insns
      is_start1 any1 i1)
    (is_start, any, i)

/-- [ebpf_validate::mark_sub_program_starts]:
    Source: 'src/lib.rs', lines 847:0-860:1 -/
@[reducible]
def mark_sub_program_starts
  (insns : Slice Insn) (is_start : alloc.vec.Vec Bool) :
  Result (Bool × (alloc.vec.Vec Bool))
  := do
  mark_sub_program_starts_loop insns is_start false 0#usize

/-- [ebpf_validate::check_self_contained_sub_programs]: loop body 0:
    Source: 'src/lib.rs', lines 916:2-922:1
    Visibility: public -/
@[rust_loop_body]
def check_self_contained_sub_programs_loop.body
  (insns : Slice Insn) (num_insns : Std.Usize) (is_start : alloc.vec.Vec Bool)
  (start : Std.Usize) :
  Result (ControlFlow Std.Usize (core.result.Result Unit Reject))
  := do
  if start < num_insns
  then
    let s := alloc.vec.Vec.deref is_start
    let «end» ← sub_program_end s start
    let r ← check_sub_program insns start «end»
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ => ok (cont «end»)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Unit (core.convert.FromSame Reject) residual
      ok (done r1)
  else ok (done (core.result.Result.Ok ()))

/-- [ebpf_validate::check_self_contained_sub_programs]: loop 0:
    Source: 'src/lib.rs', lines 916:2-922:1
    Visibility: public -/
@[rust_loop]
def check_self_contained_sub_programs_loop
  (insns : Slice Insn) (num_insns : Std.Usize) (is_start : alloc.vec.Vec Bool)
  (start : Std.Usize) :
  Result (core.result.Result Unit Reject)
  := do
  loop
    (fun start1 => check_self_contained_sub_programs_loop.body insns num_insns
      is_start start1)
    start

/-- [ebpf_validate::check_self_contained_sub_programs]:
    Source: 'src/lib.rs', lines 907:0-922:1
    Visibility: public -/
def check_self_contained_sub_programs
  (insns : Slice Insn) : Result (core.result.Result Unit Reject) := do
  let num_insns := Slice.len insns
  let is_start ← alloc.vec.from_elem core.clone.CloneBool false num_insns
  let (b, is_start1) ← mark_sub_program_starts insns is_start
  if b
  then
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Bool)
        is_start1 0#usize
    let is_start2 := index_mut_back true
    check_self_contained_sub_programs_loop insns num_insns is_start2 0#usize
  else ok (core.result.Result.Ok ())

/-- [ebpf_validate::validate]: loop body 0:
    Source: 'src/lib.rs', lines 826:2-835:1
    Visibility: public -/
@[rust_loop_body]
def validate_loop.body
  (i : Std.Usize) (b : Bool) (b1 : Bool) (known_helpers : Slice Std.U32)
  (insns : Slice Insn) (external_calls : Slice Bool) (num_insns : Std.Usize)
  (i1 : Std.Usize) :
  Result (ControlFlow Std.Usize (core.result.Result Unit Reject))
  := do
  if i1 < num_insns
  then
    let r ←
      check_slot
        {
          instruction_limit := i,
          has_dispatcher := b,
          accept_every_helper := b1
        } known_helpers insns external_calls i1
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if val
      then let i2 ← i1 + 2#usize
           ok (cont i2)
      else let i2 ← i1 + 1#usize
           ok (cont i2)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Unit (core.convert.FromSame Reject) residual
      ok (done r1)
  else let r ← check_self_contained_sub_programs insns
       ok (done r)

/-- [ebpf_validate::validate]: loop 0:
    Source: 'src/lib.rs', lines 826:2-835:1
    Visibility: public -/
@[rust_loop]
def validate_loop
  (i : Std.Usize) (b : Bool) (b1 : Bool) (known_helpers : Slice Std.U32)
  (insns : Slice Insn) (external_calls : Slice Bool) (num_insns : Std.Usize)
  (i1 : Std.Usize) :
  Result (core.result.Result Unit Reject)
  := do
  loop
    (fun i2 => validate_loop.body i b b1 known_helpers insns external_calls
      num_insns i2)
    i1

/-- [ebpf_validate::validate]:
    Source: 'src/lib.rs', lines 815:0-835:1
    Visibility: public -/
def validate
  (config : Config) (known_helpers : Slice Std.U32) (insns : Slice Insn)
  (external_calls : Slice Bool) :
  Result (core.result.Result Unit Reject)
  := do
  let i := Slice.len insns
  if i >= config.instruction_limit
  then ok (core.result.Result.Err Reject.TooManyInstructions)
  else
    let num_insns := Slice.len insns
    validate_loop config.instruction_limit config.has_dispatcher
      config.accept_every_helper known_helpers insns external_calls num_insns
      0#usize

end ebpf_validate
